[github]

# Information for securely interacting with GitHub. These are found/generated
# under <https://github.com/settings/applications>.

# A GitHub personal access token
access_token = ""

# A GitHub oauth application for this instance of homu:
app_client_id = ""
app_client_secret = ""

[git]

# Use the local Git command. Required to use some advanced features. It also
# speeds up Travis by reducing temporary commits
#local_git = false

# SSH private key. Needed only when the local Git command is used
#ssh_key = """
#"""

# By default, Homu extracts the name+email from the Github account.  However,
# you may want to use a private email for the account, and associate the commits
# with a public email address.
#user = "Some Cool Project Bot"
#email = "coolprojectbot-devel@example.com"

[web]

# The port homu listens on
port = 54856

# Synchronize all open PRs on startup
#sync_on_start = false

# An example configuration for repository (there can be many of these)
[repo.NAME]

# github.com/<owner>/<name>
owner = ""
name = ""

# who has r+ rights?
reviewers = ["barosl", "graydon"]
# Alternatively, set this to allow any github collaborator;
# note that you can *also* specify reviewers above.
# auth_collaborators = true

# who has 'try' rights? (try, retry, force, clean, prioritization)
try_users = []

# Keep the commit history linear. Requires the local Git command
#linear = false

# Auto-squash commits. Requires the local Git command
#autosquash = true

# If the PR already has the same success statuses that we expect on the auto
# branch, then push directly to branch if safe to do so. Requires the local Git
# command.
#status_based_exemption = false

## branch names (these settings here are the defaults)
#[repo.NAME.branch]
#
#auto = "auto"
#try = "try"
#rollup = "rollup"

[repo.NAME.github]

# arbitrary secret (e.g. openssl rand -hex 20)
secret = ""

## Use buildbot for running tests
#[repo.NAME.buildbot]
#
#url = ""
#secret = ""
#
#builders = ["auto-linux", "auto-mac"]
#try_builders = ["try-linux", "try-mac"]
#
#username = ""
#password = ""

## Use travis for running tests
#[repo.NAME.travis]
#
## found under <https://travis-ci.org/profile/info>.
#token = ""

## Use the Status API
#[repo.NAME.status.LABEL]
#
## String label set by status updates
#context = ""
#
## Equivalent context to look for on the PR itself if checking whether the
## build should be exempted. If omitted, looks for the same context. This is
## only used if status_based_exemption is true.
#pr_context = ""

## The database homu uses
#[db]
#
## SQLite file
#file = "main.db"
